# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bundle_update_interactive` gem.
# Please instead update this file by running `bin/tapioca gem bundle_update_interactive`.


# lib/bundle_update_interactive/string_helper.rb
#
# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive.rb:11
module BundleUpdateInteractive
  class << self
    # Returns the value of attribute pastel.
    #
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive.rb:13
    def pastel; end

    # Sets the attribute pastel
    #
    # @param value the value to set the attribute pastel to.
    #
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive.rb:13
    def pastel=(_arg0); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/bundler_commands.rb:7
module BundleUpdateInteractive::BundlerCommands
  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/bundler_commands.rb:13
    def lock; end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/bundler_commands.rb:29
    def parse_outdated(*gems); end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/bundler_commands.rb:20
    def read_updated_lockfile(*gems); end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/bundler_commands.rb:9
    def update_gems_conservatively(*gems); end

    private

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/bundler_commands.rb:39
    def bundle_bin; end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:6
class BundleUpdateInteractive::CLI
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:7
  def run(argv: T.unsafe(nil)); end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:61
  def generate_report(options); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:96
  def handle_exception(error); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:49
  def legend; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:72
  def populate_vulnerabilities_and_changelogs_concurrently(report); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:87
  def progress(message, items, &block); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:34
  def puts_gemfile_modified_notice; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:38
  def puts_legend_and_withheld_gems(report); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli.rb:83
  def whisper(message); end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:10
class BundleUpdateInteractive::CLI::MultiSelect
  extend ::BundleUpdateInteractive::StringHelper

  # @return [MultiSelect] a new instance of MultiSelect
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:62
  def initialize(title:, table:, opener: T.unsafe(nil), prompt: T.unsafe(nil)); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:75
  def prompt; end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:84
  def help; end

  # Returns the value of attribute opener.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:82
  def opener; end

  # Returns the value of attribute pastel.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:82
  def pastel; end

  # Returns the value of attribute table.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:82
  def table; end

  # Returns the value of attribute title.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:82
  def title; end

  # Returns the value of attribute tty_prompt.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:82
  def tty_prompt; end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:51
    def prompt_for_gems_to_update(outdated_gems, prompt: T.unsafe(nil)); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:13
class BundleUpdateInteractive::CLI::MultiSelect::List < ::TTY::Prompt::MultiList
  # @return [List] a new instance of List
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:14
  def initialize(prompt, **options); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:33
  def keyctrl_a(*_arg0); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:34
  def keyctrl_r(*_arg0); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:36
  def keypress(event); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:32
  def reverse_selection(*_arg0); end

  # Unregister tty-prompt's default ctrl-a and ctrl-r bindings
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:31
  def select_all(*_arg0); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:26
  def selected_names; end

  private

  # Returns the value of attribute opener.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/multi_select.rb:48
  def opener; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:7
class BundleUpdateInteractive::CLI::Options
  # @return [Options] a new instance of Options
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:102
  def initialize; end

  # Sets the attribute commit
  #
  # @param value the value to set the attribute commit to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:100
  def commit=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:109
  def commit?; end

  # Returns the value of attribute exclusively.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:99
  def exclusively; end

  # Sets the attribute exclusively
  #
  # @param value the value to set the attribute exclusively to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:99
  def exclusively=(_arg0); end

  # Sets the attribute latest
  #
  # @param value the value to set the attribute latest to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:100
  def latest=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:113
  def latest?; end

  # Sets the attribute only_explicit
  #
  # @param value the value to set the attribute only_explicit to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:100
  def only_explicit=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:117
  def only_explicit?; end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:21
    def help; end

    # @raise [Error]
    #
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:9
    def parse(argv = T.unsafe(nil)); end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:17
    def summary; end

    private

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:64
    def build_parser(options); end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/options.rb:60
    def pastel; end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:8
class BundleUpdateInteractive::CLI::Row < ::SimpleDelegator
  # @return [Row] a new instance of Row
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:15
  def initialize(outdated_gem); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:47
  def apply_semver_highlight(value); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:43
  def formatted_changelog_uri; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:24
  def formatted_current_version; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:20
  def formatted_gem_name; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:35
  def formatted_gemfile_groups; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:39
  def formatted_gemfile_requirement; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:28
  def formatted_updated_version; end

  private

  # Returns the value of attribute pastel.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:54
  def pastel; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/row.rb:9
BundleUpdateInteractive::CLI::Row::SEMVER_COLORS = T.let(T.unsafe(nil), Hash)

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:7
class BundleUpdateInteractive::CLI::Table
  # @return [Table] a new instance of Table
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:34
  def initialize(gems, columns); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:49
  def gem_names; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:62
  def render; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:57
  def render_gem(name); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:53
  def render_header; end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:79
  def calculate_column_widths; end

  # Returns the value of attribute column_widths.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:70
  def column_widths; end

  # Returns the value of attribute headers.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:70
  def headers; end

  # Returns the value of attribute pastel.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:70
  def pastel; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:72
  def render_row(row); end

  # Returns the value of attribute rows.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:70
  def rows; end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:21
    def updatable(gems); end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/cli/table.rb:9
    def withheld(gems); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:6
class BundleUpdateInteractive::ChangelogLocator
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:52
  def find_changelog_uri(name:, version: T.unsafe(nil)); end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:65
  def fetch_rubygems_data(name, version); end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:10
BundleUpdateInteractive::ChangelogLocator::EXT_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:9
BundleUpdateInteractive::ChangelogLocator::FILE_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:7
BundleUpdateInteractive::ChangelogLocator::GITHUB_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:12
class BundleUpdateInteractive::ChangelogLocator::GitHubRepo
  # @return [GitHubRepo] a new instance of GitHubRepo
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:22
  def initialize(path); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:26
  def discover_changelog_uri(version); end

  # Returns the value of attribute path.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:20
  def path; end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:40
  def fetch_repo_html(follow_redirect:); end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:13
    def from_uris(*uris); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/changelog_locator.rb:8
BundleUpdateInteractive::ChangelogLocator::URI_KEYS = T.let(T.unsafe(nil), Array)

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/error.rb:4
class BundleUpdateInteractive::Error < ::StandardError; end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/gemfile.rb:6
class BundleUpdateInteractive::Gemfile
  # @return [Gemfile] a new instance of Gemfile
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/gemfile.rb:14
  def initialize(dependencies); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/gemfile.rb:18
  def [](name); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/gemfile.rb:22
  def dependencies; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/gemfile.rb:26
  def gem_names; end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/gemfile.rb:7
    def parse(path = T.unsafe(nil)); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:6
class BundleUpdateInteractive::GitCommitter
  # @return [GitCommitter] a new instance of GitCommitter
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:7
  def initialize(updater); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:11
  def apply_updates_as_individual_commits(*gem_names); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:26
  def format_commit_message(outdated_gem); end

  private

  # @raise [Error]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:42
  def assert_git_executable!; end

  # @raise [Error]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:52
  def assert_working_directory_clean!; end

  # Returns the value of attribute updater.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/git_committer.rb:40
  def updater; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:8
module BundleUpdateInteractive::HTTP
  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:32
    def get(url); end

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:36
    def head(url); end

    private

    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:42
    def http(method, url_string); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:15
class BundleUpdateInteractive::HTTP::Error
  # @return [Error] a new instance of Error
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:18
  def initialize(exception); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:22
  def code; end

  # Returns the value of attribute exception.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:16
  def exception; end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:26
  def success?; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:9
module BundleUpdateInteractive::HTTP::Success
  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/http.rb:10
  def success?; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:4
module BundleUpdateInteractive::Latest; end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:5
class BundleUpdateInteractive::Latest::GemRequirement
  # @return [GemRequirement] a new instance of GemRequirement
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:17
  def initialize(parts:, operator: T.unsafe(nil), parsed_from: T.unsafe(nil)); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:51
  def ==(other); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:23
  def exact?; end

  # Returns the value of attribute operator.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:15
  def operator; end

  # Returns the value of attribute parts.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:15
  def parts; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:27
  def relax; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:34
  def shift(new_version); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:43
  def slice(amount); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:47
  def to_s; end

  private

  # Returns the value of attribute parsed_from.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:59
  def parsed_from; end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gem_requirement.rb:6
    def parse(version); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:5
class BundleUpdateInteractive::Latest::GemfileEditor
  # @return [GemfileEditor] a new instance of GemfileEditor
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:6
  def initialize(gemfile_path: T.unsafe(nil), lockfile_path: T.unsafe(nil)); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:18
  def shift_gemfile; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:11
  def with_relaxed_gemfile; end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:43
  def find_rewritable_gem_names(contents); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:59
  def gem_declaration_re(gem_name); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:63
  def gem_declaration_with_requirement_re(gem_name); end

  # Returns the value of attribute gemfile_path.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:29
  def gemfile_path; end

  # Returns the value of attribute lockfile_path.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:29
  def lockfile_path; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:31
  def modify_gemfile(&block); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/gemfile_editor.rb:50
  def rewrite_contents(gem_name, contents); end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:8
class BundleUpdateInteractive::Latest::Updater < ::BundleUpdateInteractive::Updater
  # @return [Updater] a new instance of Updater
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:9
  def initialize(editor: T.unsafe(nil), **kwargs); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:15
  def apply_updates(*_arg0, **_arg1); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:22
  def modified_gemfile?; end

  private

  # Returns the value of attribute editor.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:28
  def editor; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:30
  def find_updatable_gems; end

  # Overrides the default Updater implementation.
  # When updating the latest gems, by definition nothing is withheld, so we can skip this.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/latest/updater.rb:36
  def find_withheld_gems(**_arg0); end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:7
class BundleUpdateInteractive::Lockfile
  # @return [Lockfile] a new instance of Lockfile
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:13
  def initialize(specs); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:31
  def [](gem_name); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:27
  def entries; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:35
  def gems_exclusively_installed_by(gemfile:, groups:); end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:49
  def build_entry(spec, exact); end

  # Returns the value of attribute entries_by_name.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:47
  def entries_by_name; end

  # Returns the value of attribute specs_by_name.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:47
  def specs_by_name; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:54
  def traverse_transient_dependencies(*gem_names); end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile.rb:8
    def parse(lockfile_contents = T.unsafe(nil)); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:4
class BundleUpdateInteractive::LockfileEntry
  # @return [LockfileEntry] a new instance of LockfileEntry
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:7
  def initialize(spec, exact_dependencies, exact_requirement); end

  # Returns the value of attribute exact_dependencies.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:5
  def exact_dependencies; end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:31
  def exact_requirement?; end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:43
  def git_source?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:39
  def git_source_uri; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:35
  def git_version; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:13
  def name; end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:21
  def older_than?(updated_entry); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:47
  def rubygems_source?; end

  # Returns the value of attribute spec.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:5
  def spec; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/lockfile_entry.rb:17
  def version; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:4
class BundleUpdateInteractive::OutdatedGem
  # @return [OutdatedGem] a new instance of OutdatedGem
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:16
  def initialize(**attrs); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:35
  def changelog_uri; end

  # Sets the attribute changelog_uri
  #
  # @param value the value to set the attribute changelog_uri to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:14
  def changelog_uri=(_arg0); end

  # Returns the value of attribute current_git_version.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def current_git_version; end

  # Sets the attribute current_git_version
  #
  # @param value the value to set the attribute current_git_version to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def current_git_version=(_arg0); end

  # Returns the value of attribute current_version.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def current_version; end

  # Sets the attribute current_version
  #
  # @param value the value to set the attribute current_version to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def current_version=(_arg0); end

  # Returns the value of attribute gemfile_groups.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def gemfile_groups; end

  # Sets the attribute gemfile_groups
  #
  # @param value the value to set the attribute gemfile_groups to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def gemfile_groups=(_arg0); end

  # Returns the value of attribute gemfile_requirement.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def gemfile_requirement; end

  # Sets the attribute gemfile_requirement
  #
  # @param value the value to set the attribute gemfile_requirement to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def gemfile_requirement=(_arg0); end

  # Returns the value of attribute git_source_uri.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def git_source_uri; end

  # Sets the attribute git_source_uri
  #
  # @param value the value to set the attribute git_source_uri to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def git_source_uri=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:52
  def git_version_changed?; end

  # Returns the value of attribute name.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def name; end

  # Sets the attribute name
  #
  # @param value the value to set the attribute name to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def name=(_arg0); end

  # Sets the attribute rubygems_source
  #
  # @param value the value to set the attribute rubygems_source to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:14
  def rubygems_source=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:31
  def rubygems_source?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:23
  def semver_change; end

  # Returns the value of attribute updated_git_version.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def updated_git_version; end

  # Sets the attribute updated_git_version
  #
  # @param value the value to set the attribute updated_git_version to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def updated_git_version=(_arg0); end

  # Returns the value of attribute updated_version.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def updated_version; end

  # Sets the attribute updated_version
  #
  # @param value the value to set the attribute updated_version to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:5
  def updated_version=(_arg0); end

  # Sets the attribute vulnerable
  #
  # @param value the value to set the attribute vulnerable to.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:14
  def vulnerable=(_arg0); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:27
  def vulnerable?; end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:88
  def bitbucket_cloud_repo; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:64
  def build_git_diff_url; end

  # Returns the value of attribute changelog_locator.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:58
  def changelog_locator; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:76
  def github_repo; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:82
  def gitlab_repo; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/outdated_gem.rb:60
  def locate_changelog_uri; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:9
class BundleUpdateInteractive::Report
  # @return [Report] a new instance of Report
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:12
  def initialize(current_lockfile:, withheld_gems:, updatable_gems:); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:22
  def all_gems; end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:18
  def empty?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:26
  def scan_for_vulnerabilities!; end

  # Returns the value of attribute updatable_gems.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:10
  def updatable_gems; end

  # Returns the value of attribute withheld_gems.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:10
  def withheld_gems; end

  private

  # Returns the value of attribute current_lockfile.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/report.rb:42
  def current_lockfile; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:4
class BundleUpdateInteractive::SemverChange
  # @return [SemverChange] a new instance of SemverChange
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:7
  def initialize(old_version, new_version); end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:31
  def any?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:35
  def format; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:24
  def major?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:24
  def minor?; end

  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:27
  def none?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:24
  def patch?; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:17
  def severity; end

  private

  # Returns the value of attribute diff_segments.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:44
  def diff_segments; end

  # Returns the value of attribute same_segments.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:44
  def same_segments; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/semver_change.rb:5
BundleUpdateInteractive::SemverChange::SEVERITIES = T.let(T.unsafe(nil), Array)

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/string_helper.rb:5
module BundleUpdateInteractive::StringHelper
  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/string_helper.rb:6
  def pluralize(count, singular, plural = T.unsafe(nil)); end

  class << self
    # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/string_helper.rb:10
    def pluralize(count, singular, plural = T.unsafe(nil)); end
  end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/thread_pool.rb:6
class BundleUpdateInteractive::ThreadPool
  include ::Concurrent::Promises::FactoryMethods::Configuration
  include ::Concurrent::Promises::FactoryMethods

  # @return [ThreadPool] a new instance of ThreadPool
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/thread_pool.rb:9
  def initialize(max_threads:); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/thread_pool.rb:17
  def default_executor; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:4
class BundleUpdateInteractive::Updater
  # @return [Updater] a new instance of Updater
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:5
  def initialize(groups: T.unsafe(nil), only_explicit: T.unsafe(nil)); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:19
  def apply_updates(*gem_names); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:12
  def generate_report; end

  # Overridden by Latest::Updater subclass
  #
  # @return [Boolean]
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:30
  def modified_gemfile?; end

  private

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:72
  def build_outdated_gem(name, updated_version, updated_git_version); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:46
  def build_outdated_gems(lockfile_contents); end

  # Returns the value of attribute candidate_gems.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:36
  def candidate_gems; end

  # Returns the value of attribute current_lockfile.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:36
  def current_lockfile; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:88
  def expand_gems_with_exact_dependencies(*gem_names); end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:38
  def find_updatable_gems; end

  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:58
  def find_withheld_gems(exclude: T.unsafe(nil)); end

  # Returns the value of attribute gemfile.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:36
  def gemfile; end

  # Returns the value of attribute only_explicit.
  #
  # pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/updater.rb:36
  def only_explicit; end
end

# pkg:gem/bundle_update_interactive#lib/bundle_update_interactive/version.rb:4
BundleUpdateInteractive::VERSION = T.let(T.unsafe(nil), String)
