# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `bundler-audit` gem.
# Please instead update this file by running `bin/tapioca gem bundler-audit`.


# pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:22
module Bundler::Audit; end

# Represents an advisory loaded from the {Database}.
#
# pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:38
class Bundler::Audit::Advisory < ::Struct
  # Compares two advisories.
  #
  # @param other [Advisory]
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:210
  def ==(other); end

  # Determines how critical the vulnerability is.
  #
  # @return [:none, :low, :medium, :high, :critical, nil] The criticality of the vulnerability based on the CVSS score.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:138
  def criticality; end

  # The CVE identifier.
  #
  # @return [String, nil]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:93
  def cve_id; end

  # The GHSA (GitHub Security Advisory) identifier
  #
  # @return [String, nil]
  # @since 0.7.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:113
  def ghsa_id; end

  # Return a compacted list of all ids
  #
  # @return [Array<String>]
  # @since 0.7.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:124
  def identifiers; end

  # The OSVDB identifier.
  #
  # @return [String, nil]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:102
  def osvdb_id; end

  # Checks whether the version is patched against the advisory.
  #
  # @param version [Gem::Version] The version to compare against {#patched_versions}.
  # @return [Boolean] Specifies whether the version is patched against the advisory.
  # @since 0.2.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:184
  def patched?(version); end

  # Converts the advisory to a Hash.
  #
  # @return [Hash{Symbol => Object}]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:219
  def to_h; end

  # Returns the value of attribute id
  #
  # @return [Object] the current value of id
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:225
  def to_s; end

  # Checks whether the version is not affected by the advisory.
  #
  # @param version [Gem::Version] The version to compare against {#unaffected_versions}.
  # @return [Boolean] Specifies whether the version is not affected by the advisory.
  # @since 0.2.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:167
  def unaffected?(version); end

  # Checks whether the version is vulnerable to the advisory.
  #
  # @param version [Gem::Version] The version to compare against {#patched_versions}.
  # @return [Boolean] Specifies whether the version is vulnerable to the advisory or not.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:199
  def vulnerable?(version); end

  class << self
    # Loads the advisory from a YAML file.
    #
    # @api semipublic
    # @param path [String] The path to the advisory YAML file.
    # @return [Advisory]
    #
    # pkg:gem/bundler-audit#lib/bundler/audit/advisory.rb:50
    def load(path); end
  end
end

# Class for storing and validating configuration for running the auditor.
#
# @since 0.8.0
#
# pkg:gem/bundler-audit#lib/bundler/audit/configuration.rb:28
class Bundler::Audit::Configuration
  # Initializes the configuration.
  #
  # @option config
  # @param config [Hash] The configuration hash.
  # @return [Configuration] a new instance of Configuration
  # @since 0.8.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/configuration.rb:102
  def initialize(config = T.unsafe(nil)); end

  # The list of advisory IDs to ignore.
  #
  # @return [Set<String>]
  # @since 0.8.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/configuration.rb:91
  def ignore; end

  class << self
    # A constructor method for loading configuration from a YAML file.
    #
    # @param file_path [String] Path to the YAML file holding the configuration.
    # @raise [FileNotFound] Will raise a file not found error when the path to the
    #   configuration YAML file does not exist.
    # @raise [InvalidConfigurationError] Will raise an invalid configuration error indicating what in the
    #   YAML file is invalid for the configuration.
    # @return [Configuration] A Configuration object containing the config hash loaded from the
    #   file passed.
    # @since 0.8.0
    #
    # pkg:gem/bundler-audit#lib/bundler/audit/configuration.rb:53
    def load(file_path); end
  end
end

# @since 0.8.0
#
# pkg:gem/bundler-audit#lib/bundler/audit/configuration.rb:32
class Bundler::Audit::Configuration::FileNotFound < ::StandardError; end

# @since 0.8.0
#
# pkg:gem/bundler-audit#lib/bundler/audit/configuration.rb:29
class Bundler::Audit::Configuration::InvalidConfigurationError < ::StandardError; end

# Represents the directory of advisories, grouped by gem name
# and CVE number.
#
# pkg:gem/bundler-audit#lib/bundler/audit/database.rb:29
class Bundler::Audit::Database
  # Initializes the Advisory Database.
  #
  # @param path [String] The path to the advisory database.
  # @raise [ArgumentError] The path was not a directory.
  # @return [Database] a new instance of Database
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:62
  def initialize(path = T.unsafe(nil)); end

  # Enumerates over every advisory in the database.
  #
  # @return [Enumerator] If no block is given, an Enumerator will be returned.
  # @yield [advisory] If a block is given, it will be passed each advisory.
  # @yieldparam advisory [Advisory] An advisory from the database.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:265
  def advisories(&block); end

  # Enumerates over advisories for the given gem.
  #
  # @param name [String] The gem name to lookup.
  # @return [Enumerator] If no block is given, an Enumerator will be returned.
  # @yield [advisory] If a block is given, each advisory for the given gem will be yielded.
  # @yieldparam advisory [Advisory] An advisory for the given gem.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:288
  def advisories_for(name); end

  # Verifies whether the gem is effected by any advisories.
  #
  # @param gem [Gem::Specification] The gem to verify.
  # @return [Enumerator] If no block is given, an Enumerator will be returned.
  # @yield [advisory] If a block is given, it will be passed advisories that effect
  #   the gem.
  # @yieldparam advisory [Advisory] An advisory that effects the specific version of the gem.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:312
  def check_gem(gem); end

  # The last commit ID of the repository.
  #
  # @return [String, nil] The commit hash or `nil` if the database is not a git repository.
  # @since 0.9.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:228
  def commit_id; end

  # Determines if the database is a git repository.
  #
  # @return [Boolean]
  # @since 0.8.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:180
  def git?; end

  # Inspects the database.
  #
  # @return [String] The inspected database.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:348
  def inspect; end

  # Determines the time when the database was last updated.
  #
  # @return [Time]
  # @since 0.8.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:243
  def last_updated_at; end

  # The path to the advisory database.
  #
  # @return [String]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:51
  def path; end

  # The number of advisories within the database.
  #
  # @return [Integer] The number of advisories.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:328
  def size; end

  # Converts the database to a String.
  #
  # @return [String] The path to the database.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:338
  def to_s; end

  # Updates the ruby-advisory-db.
  #
  # @option options
  # @param options [Hash] Additional options.
  # @raise [UpdateFailed] Could not update the ruby-advisory-db git repository.
  # @return [true, nil] * `true` - the ruby-advisory-db git repository was successfully
  #   updated.
  #   * `nil` - the ruby-advisory-db is not a git repository or the `git`
  #   command is not installed.
  # @since 0.8.0
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:204
  def update!(options = T.unsafe(nil)); end

  protected

  # Enumerates over every advisory path in the database.
  #
  # @yield [path] The given block will be passed each advisory path.
  # @yieldparam path [String] A path to an advisory `.yml` file.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:363
  def each_advisory_path(&block); end

  # Enumerates over the advisories for the given gem.
  #
  # @param name [String] The gem of the gem.
  # @yield [path] The given block will be passed each advisory path.
  # @yieldparam path [String] A path to an advisory `.yml` file.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:379
  def each_advisory_path_for(name, &block); end

  class << self
    # Downloads the ruby-advisory-db.
    #
    # @note Requires network access.
    # @option options
    # @option options
    # @param options [Hash] Additional options.
    # @raise [DownloadFailed] Indicates that the download failed.
    # @return [Database] The newly downloaded database.
    # @since 0.8.0
    #
    # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:117
    def download(options = T.unsafe(nil)); end

    # Tests whether the database exists.
    #
    # @param path [String] The given path of the database to check.
    # @return [Boolean]
    # @since 0.8.0
    #
    # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:90
    def exists?(path = T.unsafe(nil)); end

    # The default path for the database.
    #
    # @return [String] The path to the database directory.
    #
    # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:76
    def path; end

    # Updates the ruby-advisory-db.
    #
    # @deprecated Use {#update!} instead.
    # @note Requires network access.
    # @option options
    # @param options [Hash] Additional options.
    # @raise [ArgumentError] Invalid options were given.
    # @return [Boolean] Specifies whether the update was successful.
    # @since 0.3.0
    #
    # pkg:gem/bundler-audit#lib/bundler/audit/database.rb:157
    def update!(options = T.unsafe(nil)); end
  end
end

# Default path to the ruby-advisory-db.
#
# @since 0.8.0
#
# pkg:gem/bundler-audit#lib/bundler/audit/database.rb:46
Bundler::Audit::Database::DEFAULT_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/bundler-audit#lib/bundler/audit/database.rb:31
class Bundler::Audit::Database::DownloadFailed < ::RuntimeError; end

# Git URL of the ruby-advisory-db.
#
# pkg:gem/bundler-audit#lib/bundler/audit/database.rb:38
Bundler::Audit::Database::URL = T.let(T.unsafe(nil), String)

# Path to the user's copy of the ruby-advisory-db.
#
# pkg:gem/bundler-audit#lib/bundler/audit/database.rb:41
Bundler::Audit::Database::USER_PATH = T.let(T.unsafe(nil), String)

# pkg:gem/bundler-audit#lib/bundler/audit/database.rb:34
class Bundler::Audit::Database::UpdateFailed < ::RuntimeError; end

# Represents the result of a scan.
#
# pkg:gem/bundler-audit#lib/bundler/audit/report.rb:11
class Bundler::Audit::Report
  include ::Enumerable

  # Initializes the report.
  #
  # @param results [#each]
  # @return [Report] a new instance of Report
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:45
  def initialize(results = T.unsafe(nil)); end

  # Appends a result to the report.
  #
  # @param result [InsecureSource, UnpatchedGem]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:74
  def <<(result); end

  # @return [Array<Advisory>]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:112
  def advisories; end

  # The time when the report was generated.
  #
  # @return [Time]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:23
  def created_at; end

  # Enumerates over the results.
  #
  # @return [Enumerator]
  # @yield [result]
  # @yieldparam result [Results::InsecureSource, Results::UnpatchedGem]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:65
  def each(&block); end

  # @return [Enumerator]
  # @yield [advisory]
  # @yieldparam advisory [Advisory]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:103
  def each_advisory; end

  # @return [Enumerator]
  # @yield [gem]
  # @yieldparam [Gem::Specification]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:123
  def each_vulnerable_gem; end

  # The insecure sources results.
  #
  # @return [Array<Results::InsecureSources>]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:33
  def insecure_sources; end

  # The list of all results.
  #
  # @return [Array<Results::Result>]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:28
  def results; end

  # @return [Hash{Symbol => Object}]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:139
  def to_h; end

  # The unpatched gems results.
  #
  # @return [Array<Results::UnpatchedGems>]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:38
  def unpatched_gems; end

  # The version of `bundler-audit` which created the report object.
  #
  # @return [String]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:18
  def version; end

  # Determines if there were vulnerabilities found.
  #
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:92
  def vulnerable?; end

  # @return [Array<Gem::Specification>]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/report.rb:132
  def vulnerable_gems; end
end

# pkg:gem/bundler-audit#lib/bundler/audit/results/result.rb:3
module Bundler::Audit::Results; end

# Represents an insecure gem source (ex: `git://...` or `http://...`).
#
# pkg:gem/bundler-audit#lib/bundler/audit/results/insecure_source.rb:26
class Bundler::Audit::Results::InsecureSource < ::Bundler::Audit::Results::Result
  # Initializes the insecure source result.
  #
  # @param source [URI::Generic, URI::HTTP] The insecure `git://` or `http://` URI.
  # @return [InsecureSource] a new instance of InsecureSource
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/insecure_source.rb:39
  def initialize(source); end

  # Compares the insecure source with another result.
  #
  # @param other [Result]
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/insecure_source.rb:50
  def ==(other); end

  # The insecure `git://` or `http://` URI.
  #
  # @return [URI::Generic, URI::HTTP]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/insecure_source.rb:31
  def source; end

  # Converts the insecure source into a Hash.
  #
  # @return [Hash{Symbol => Object}]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/insecure_source.rb:68
  def to_h; end

  # Converts the insecure source result to a String.
  #
  # @return [String]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/insecure_source.rb:59
  def to_s; end
end

# @abstract
#
# pkg:gem/bundler-audit#lib/bundler/audit/results/result.rb:7
class Bundler::Audit::Results::Result
  # @abstract
  # @raise [NotImplementedError]
  # @return [Hash{Symbol => Object}]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/result.rb:14
  def to_h; end
end

# Represents a gem version that has known vulnerabilities and needs to be
# upgraded.
#
# pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:29
class Bundler::Audit::Results::UnpatchedGem < ::Bundler::Audit::Results::Result
  # Initializes the unpatched gem result.
  #
  # @param advisory [Advisory] The advisory documenting the vulnerability.
  # @param gem [Gem::Specification] The specification of the vulnerable gem.
  # @return [UnpatchedGem] a new instance of UnpatchedGem
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:50
  def initialize(gem, advisory); end

  # Compares the unpatched gem to another result.
  #
  # @param other [Result]
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:62
  def ==(other); end

  # The advisory documenting the vulnerability.
  #
  # @return [Advisory]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:39
  def advisory; end

  # The specification of the vulnerable gem.
  #
  # @return [Gem::Specification]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:34
  def gem; end

  # Converts the unpatched gem to a Hash.
  #
  # @return [Hash{Symbol => Object}]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:84
  def to_h; end

  # Converts the unpatched gem result into a String.
  #
  # @return [String]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/results/unpatched_gem.rb:75
  def to_s; end
end

# Scans a `Gemfile.lock` for security issues.
#
# pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:37
class Bundler::Audit::Scanner
  # Initializes a scanner.
  #
  # @param config_dot_file [String] The file name of the bundler-audit config file.
  # @param database [Database] The database to scan against.
  # @param gemfile_lock [String] Alternative name for the `Gemfile.lock` file.
  # @param root [String] The path to the project root.
  # @raise [Bundler::GemfileLockNotFound] The `gemfile_lock` file could not be found within the `root`
  #   directory.
  # @return [Scanner] a new instance of Scanner
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:77
  def initialize(root = T.unsafe(nil), gemfile_lock = T.unsafe(nil), database = T.unsafe(nil), config_dot_file = T.unsafe(nil)); end

  # The configuration loaded from the `.bundler-audit.yml` file from the
  # project.
  #
  # @return [Hash]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:56
  def config; end

  # The advisory database.
  #
  # @return [Database]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:42
  def database; end

  # The parsed `Gemfile.lock` from the project.
  #
  # @return [Bundler::LockfileParser]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:50
  def lockfile; end

  # Preforms a {#scan} and collects the results into a {Report report}.
  #
  # @option options
  # @param options [Hash] Additional options.
  # @return [Report]
  # @since 0.8.0
  # @yield [result] The given block will be passed the results of the scan.
  # @yieldparam result [Results::InsecureSource, Results::UnpatchedGem] A result from the scan.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:117
  def report(options = T.unsafe(nil)); end

  # Project root directory
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:45
  def root; end

  # Scans the project for issues.
  #
  # @option options
  # @param options [Hash] Additional options.
  # @return [Enumerator] If no block is given, an Enumerator will be returned.
  # @yield [result] The given block will be passed the results of the scan.
  # @yieldparam result [Results::InsecureSource, Results::UnpatchedGem] A result from the scan.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:146
  def scan(options = T.unsafe(nil), &block); end

  # Scans the gem sources in the lockfile.
  #
  # @api semipublic
  # @param options [Hash] Additional options.
  # @return [Enumerator] If no block is given, an Enumerator will be returned.
  # @since 0.4.0
  # @yield [result] The given block will be passed the results of the scan.
  # @yieldparam result [Results::InsecureSource] A result from the scan.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:174
  def scan_sources(options = T.unsafe(nil)); end

  # Scans the gem sources in the lockfile.
  #
  # @api semipublic
  # @option options
  # @param options [Hash] Additional options.
  # @return [Enumerator] If no block is given, an Enumerator will be returned.
  # @since 0.4.0
  # @yield [result] The given block will be passed the results of the scan.
  # @yieldparam result [Results::UnpatchedGem] A result from the scan.
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:218
  def scan_specs(options = T.unsafe(nil)); end

  private

  # Determines whether a host is internal.
  #
  # @param host [String] The hostname.
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:261
  def internal_host?(host); end

  # Determines whether an IP is internal.
  #
  # @param ip [String] The IPv4/IPv6 address.
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:290
  def internal_ip?(ip); end

  # Determines whether a source is internal.
  #
  # @param uri [URI, String] The URI.
  # @return [Boolean]
  #
  # pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:247
  def internal_source?(uri); end
end

# List of internal IP address ranges.
#
# @see https://tools.ietf.org/html/rfc1918#section-3
# @see https://tools.ietf.org/html/rfc4193#section-8
# @see https://tools.ietf.org/html/rfc6890#section-2.2.2
# @see https://tools.ietf.org/html/rfc6890#section-2.2.3
#
# pkg:gem/bundler-audit#lib/bundler/audit/scanner.rb:273
Bundler::Audit::Scanner::INTERNAL_SUBNETS = T.let(T.unsafe(nil), Array)

# bundler-audit version
#
# pkg:gem/bundler-audit#lib/bundler/audit/version.rb:21
Bundler::Audit::VERSION = T.let(T.unsafe(nil), String)

module Bundler::MatchRemoteMetadata
  include ::Bundler::FetchMetadata
  include ::Bundler::MatchMetadata
end
