# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `memery` gem.
# Please instead update this file by running `bin/tapioca gem memery`.


# pkg:gem/memery#lib/memery/version.rb:3
module Memery
  extend ::Memery::ModuleMethods
  include ::Memery::InstanceMethods

  mixes_in_class_methods ::Memery::ClassMethods

  class << self
    # pkg:gem/memery#lib/memery.rb:9
    def monotonic_clock; end

    # Returns the value of attribute use_hashed_arguments.
    #
    # pkg:gem/memery#lib/memery.rb:7
    def use_hashed_arguments; end

    # Sets the attribute use_hashed_arguments
    #
    # @param value the value to set the attribute use_hashed_arguments to.
    #
    # pkg:gem/memery#lib/memery.rb:7
    def use_hashed_arguments=(_arg0); end
  end
end

# pkg:gem/memery#lib/memery.rb:39
module Memery::ClassMethods
  # pkg:gem/memery#lib/memery.rb:40
  def memoize(*method_names, condition: T.unsafe(nil), ttl: T.unsafe(nil)); end

  # @return [Boolean]
  #
  # pkg:gem/memery#lib/memery.rb:52
  def memoized?(method_name); end

  # pkg:gem/memery#lib/memery.rb:59
  def method_added(name); end

  private

  # pkg:gem/memery#lib/memery.rb:76
  def define_memoized_method!(method_name, **_arg1); end

  # pkg:gem/memery#lib/memery.rb:70
  def prepend_memery_module!; end
end

# pkg:gem/memery#lib/memery.rb:80
module Memery::ClassMethods::MemoizationModule
  # pkg:gem/memery#lib/memery.rb:89
  def define_memoized_method!(klass, method_name, condition: T.unsafe(nil), ttl: T.unsafe(nil)); end

  private

  # pkg:gem/memery#lib/memery.rb:125
  def method_visibility(klass, method_name); end
end

# pkg:gem/memery#lib/memery.rb:81
class Memery::ClassMethods::MemoizationModule::Cache < ::Struct
  # @return [Boolean]
  #
  # pkg:gem/memery#lib/memery.rb:82
  def fresh?(ttl); end

  # Returns the value of attribute result
  #
  # @return [Object] the current value of result
  #
  # pkg:gem/memery#lib/memery.rb:81
  def result; end

  # Sets the attribute result
  #
  # @param value [Object] the value to set the attribute result to.
  # @return [Object] the newly set value
  #
  # pkg:gem/memery#lib/memery.rb:81
  def result=(_); end

  # Returns the value of attribute time
  #
  # @return [Object] the current value of time
  #
  # pkg:gem/memery#lib/memery.rb:81
  def time; end

  # Sets the attribute time
  #
  # @param value [Object] the value to set the attribute time to.
  # @return [Object] the newly set value
  #
  # pkg:gem/memery#lib/memery.rb:81
  def time=(_); end

  class << self
    # pkg:gem/memery#lib/memery.rb:81
    def [](*_arg0); end

    # pkg:gem/memery#lib/memery.rb:81
    def inspect; end

    # pkg:gem/memery#lib/memery.rb:81
    def keyword_init?; end

    # pkg:gem/memery#lib/memery.rb:81
    def members; end

    # pkg:gem/memery#lib/memery.rb:81
    def new(*_arg0); end
  end
end

# pkg:gem/memery#lib/memery.rb:141
module Memery::InstanceMethods
  # pkg:gem/memery#lib/memery.rb:142
  def clear_memery_cache!; end
end

# pkg:gem/memery#lib/memery.rb:24
module Memery::ModuleMethods
  # pkg:gem/memery#lib/memery.rb:25
  def included(base = T.unsafe(nil), &block); end
end

# pkg:gem/memery#lib/memery.rb:16
Memery::OUR_BLOCK = T.let(T.unsafe(nil), Proc)

# pkg:gem/memery#lib/memery/version.rb:4
Memery::VERSION = T.let(T.unsafe(nil), String)
