# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rails-reverse-proxy` gem.
# Please instead update this file by running `bin/tapioca gem rails-reverse-proxy`.


# pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:4
module ReverseProxy
  extend ::ReverseProxy

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy.rb:5
  def version; end
end

# pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:5
class ReverseProxy::Client
  # @return [Client] a new instance of Client
  # @yield [_self]
  # @yieldparam _self [ReverseProxy::Client] the object that the method was called on
  #
  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:35
  def initialize(url); end

  # Returns the value of attribute callbacks.
  #
  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:33
  def callbacks; end

  # Sets the attribute callbacks
  #
  # @param value the value to set the attribute callbacks to.
  #
  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:33
  def callbacks=(_arg0); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_complete(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_connect(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_error(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_missing(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_redirect(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_response(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_set_cookies(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:28
  def on_success(&block); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:47
  def request(env, options = T.unsafe(nil), &block); end

  # Returns the value of attribute url.
  #
  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:33
  def url; end

  # Sets the attribute url
  #
  # @param value the value to set the attribute url to.
  #
  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:33
  def url=(_arg0); end

  private

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:139
  def extract_http_request_headers(env); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:160
  def parse_cookie(cookie_str); end

  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:153
  def reconstruct_header_name(name); end
end

# pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:157
ReverseProxy::Client::COOKIE_PARAM_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:158
ReverseProxy::Client::COOKIE_SPLIT_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rails-reverse-proxy#lib/reverse_proxy/client.rb:6
ReverseProxy::Client::RackHeaders = Rack::Headers

# pkg:gem/rails-reverse-proxy#lib/reverse_proxy/controller.rb:4
module ReverseProxy::Controller
  # pkg:gem/rails-reverse-proxy#lib/reverse_proxy/controller.rb:5
  def reverse_proxy(proxy_url, options = T.unsafe(nil)); end
end
