# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `rubocop-sane` gem.
# Please instead update this file by running `bin/tapioca gem rubocop-sane`.


# pkg:gem/rubocop-sane#lib/rubocop/sane.rb:3
module RuboCop; end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:4
module RuboCop::Cop; end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:5
module RuboCop::Cop::Sane; end

# This cop enforces `assign_inside_condition` style like
# `Style/ConditionalAssignment`, but allows ternary operators.
#
# @example
#   # bad
#   foo = if condition
#   1
#   else
#   2
#   end
#
#   # bad
#   foo = case bar
#   when :a then 1
#   when :b then 2
#   end
#
#   # good - assignment inside condition
#   if condition
#   foo = 1
#   else
#   foo = 2
#   end
#
#   # good - ternary operators are allowed
#   foo = condition ? 1 : 2
#
#   # good - multiline ternary operators are allowed
#   foo = condition
#   ? 1
#   : 2
#
# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:38
class RuboCop::Cop::Sane::ConditionalAssignmentAllowTernary < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:64
  def on_and_asgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:50
  def on_casgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:48
  def on_cvasgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:49
  def on_gvasgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:47
  def on_ivasgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:43
  def on_lvasgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:52
  def on_masgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:56
  def on_op_asgn(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:60
  def on_or_asgn(node); end

  private

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:80
  def assignment_to_conditional?(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:70
  def check_assignment(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:94
  def extract_rhs(node); end
end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:41
RuboCop::Cop::Sane::ConditionalAssignmentAllowTernary::ASSIGNMENT_TYPES = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/conditional_assignment_allow_ternary.rb:39
RuboCop::Cop::Sane::ConditionalAssignmentAllowTernary::MSG = T.let(T.unsafe(nil), String)

# Enforces method replacements and prohibitions.
#
# This cop checks for usage of specified methods and either suggests
# replacements (with auto-correction) or prohibits usage entirely.
#
# @example ProhibitedMethods configuration
#   # .rubocop.yml
#   # Sane/DisallowMethods:
#   #   ProhibitedMethods:
#   #     dangerous_method:
#   #       reason: "This method is deprecated and unsafe"
#
#   # bad
#   obj.dangerous_method
# @example ReplaceMethods configuration
#   # .rubocop.yml
#   # Sane/DisallowMethods:
#   #   ReplaceMethods:
#   #     deliver_now:
#   #       with: deliver_later
#   #       reason: "`deliver_later` sends the email via background job"
#
#   # bad
#   UserMailer.welcome(user).deliver_now
#
#   # good
#   UserMailer.welcome(user).deliver_later
#
# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:35
class RuboCop::Cop::Sane::DisallowMethods < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:41
  def on_send(node); end

  private

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:86
  def build_method_hash(config); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:68
  def handle_prohibited_method(node, method_name, config); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:55
  def handle_replaceable_method(node, method_name, config); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:82
  def prohibited_methods; end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:78
  def replace_methods; end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:92
  def safe_autocorrect?; end
end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:39
RuboCop::Cop::Sane::DisallowMethods::PROHIBITED_METHOD_MSG = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/disallow_methods.rb:38
RuboCop::Cop::Sane::DisallowMethods::REPLACEABLE_METHOD_MSG = T.let(T.unsafe(nil), String)

# Enforces an empty line before comments, except when the previous line
# is the start of a block, class, method, or another comment.
#
# @example
#   # bad
#   foo = 1
#   # This is a comment
#   bar = 2
#
#   # good
#   foo = 1
#
#   # This is a comment
#   bar = 2
#
#   # good - after block/class/method start
#   def foo
#   # This comment doesn't need a blank line
#   bar
#   end
#
#   # good - consecutive comments
#   # First comment
#   # Second comment
#
#   # good - after control structure start
#   if condition
#   # Comment inside if
#   do_something
#   end
#
# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:37
class RuboCop::Cop::Sane::EmptyLineBeforeComment < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:42
  def on_new_investigation; end

  private

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:130
  def block_opener?(line); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:111
  def block_start_pattern?(line); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:50
  def check_comment(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:82
  def first_line?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:72
  def inline_comment?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:101
  def preceded_by_block_start?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:94
  def preceded_by_comment?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:86
  def preceded_by_empty_line?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:68
  def rubocop_directive?(comment); end
end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_line_before_comment.rb:40
RuboCop::Cop::Sane::EmptyLineBeforeComment::MSG = T.let(T.unsafe(nil), String)

# This cop enforces empty lines before and after multiline blocks
# such as `if/else`, `case/when`, and `begin...rescue...end`.
#
# Sorbet `sig` blocks require a blank line before, but not after,
# since they should be tightly coupled to their method definitions.
#
# @example
#   # bad
#   work_for = data.work_done_for
#   if data.present?
#   creation_date = date1
#   else
#   creation_date = date2
#   end
#   legal_start_date = date3
#
#   # good
#   work_for = data.work_done_for
#
#   if data.present?
#   creation_date = date1
#   else
#   creation_date = date2
#   end
#
#   legal_start_date = date3
#
#   # good - no blank line needed at beginning of method
#   def foo
#   if condition
#   bar
#   else
#   baz
#   end
#
#   qux
#   end
#
#   # good - no blank line needed at end of method
#   def foo
#   bar
#
#   if condition
#   baz
#   else
#   qux
#   end
#   end
#
#   # good - Sorbet sig blocks don't need blank line after
#   something
#
#   sig do
#   params(x: Integer).returns(String)
#   end
#   def foo(x)
#   x.to_s
#   end
#
#   # bad - missing blank line before begin
#   temp_file = Tempfile.new(["import", ".csv"])
#   begin
#   temp_file.write(data)
#   rescue IOError
#   handle_error
#   end
#
#   # good - blank line before begin
#   temp_file = Tempfile.new(["import", ".csv"])
#
#   begin
#   temp_file.write(data)
#   rescue IOError
#   handle_error
#   end
#
# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:82
class RuboCop::Cop::Sane::EmptyLinesAroundMultilineBlock < ::RuboCop::Cop::Base
  extend ::RuboCop::Cop::AutoCorrector

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:214
  def assignment_node?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:176
  def block_in_collection?(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:197
  def check_empty_line_after_assignment(block_node, assignment_node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:184
  def find_assignment_parent(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:236
  def followed_by_rescue?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:159
  def lambda_block?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:168
  def method_chain_block?(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:137
  def on_block(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:121
  def on_case(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:128
  def on_case_match(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:88
  def on_if(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:130
  def on_kwbegin(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:157
  def on_numblock(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:231
  def paired_methods?(prev_method, current_method); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:99
  def part_of_expression?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:218
  def preceded_by_paired_method?(node, prev_sibling); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:163
  def sig_block?(node); end

  private

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:260
  def block_keyword(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:359
  def body_siblings(parent); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:297
  def check_empty_line_after(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:274
  def check_empty_line_before(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:414
  def comment_line_before?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:404
  def empty_line_between?(node1, node2); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:314
  def first_child_of_parent?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:325
  def last_child_of_parent?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:256
  def multiline?(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:382
  def next_sibling(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:336
  def only_child_in_body?(node, parent); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:365
  def previous_sibling(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:426
  def rubocop_directive?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:421
  def rubocop_directive_after?(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:430
  def standalone_comment?(comment); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:399
  def valid_sibling?(sibling); end
end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:86
RuboCop::Cop::Sane::EmptyLinesAroundMultilineBlock::MSG_AFTER = T.let(T.unsafe(nil), String)

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/empty_lines_around_multiline_block.rb:85
RuboCop::Cop::Sane::EmptyLinesAroundMultilineBlock::MSG_BEFORE = T.let(T.unsafe(nil), String)

# Prohibits calling methods directly after `end`.
#
# This cop detects method calls chained directly on blocks, conditionals,
# and other structures that end with `end`. Such code is harder to read
# and should be refactored to assign the result to a variable first.
#
# @example
#   # bad
#   if condition
#   value
#   end.foo
#
#   # bad
#   if condition
#   value
#   end&.foo
#
#   # bad
#   array.map do |item|
#   transform(item)
#   end.compact
#
#   # good
#   result = if condition
#   value
#   end
#   result.foo
#
#   # good
#   result = array.map do |item|
#   transform(item)
#   end
#   result.compact
#
# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:40
class RuboCop::Cop::Sane::NoMethodCallAfterEnd < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:55
  def on_csend(node); end

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:51
  def on_send(node); end

  private

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:61
  def check_method_call_after_end(node); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:69
  def ends_with_end_keyword?(node); end
end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:49
RuboCop::Cop::Sane::NoMethodCallAfterEnd::BLOCK_NODES = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:43
RuboCop::Cop::Sane::NoMethodCallAfterEnd::END_KEYWORD_NODES = T.let(T.unsafe(nil), Array)

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/no_method_call_after_end.rb:41
RuboCop::Cop::Sane::NoMethodCallAfterEnd::MSG = T.let(T.unsafe(nil), String)

# Detects TODO/NOTE/FIXME comments with dates that are in the past.
#
# This cop helps ensure that dated comments are reviewed when their
# target date has passed.
#
# @example
#   # bad (when date is in the past)
#   # TODO[2024-01-01]: Remove this after migration
#   # NOTE[2023-06-15]: Temporary workaround
#   # FIXME[2024-03-01]: Fix this bug
#
#   # good (when date is in the future or today)
#   # TODO[2025-12-31]: Remove this after migration
#
# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/outdated_comments.rb:22
class RuboCop::Cop::Sane::OutdatedComments < ::RuboCop::Cop::Base
  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/outdated_comments.rb:26
  def on_new_investigation; end

  private

  # pkg:gem/rubocop-sane#lib/rubocop/cop/sane/outdated_comments.rb:36
  def check_comment(comment); end
end

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/outdated_comments.rb:23
RuboCop::Cop::Sane::OutdatedComments::COMMENT_PATTERN = T.let(T.unsafe(nil), Regexp)

# pkg:gem/rubocop-sane#lib/rubocop/cop/sane/outdated_comments.rb:24
RuboCop::Cop::Sane::OutdatedComments::MSG = T.let(T.unsafe(nil), String)

# RuboCop Sane project namespace
#
# pkg:gem/rubocop-sane#lib/rubocop/sane.rb:5
module RuboCop::Sane; end

# pkg:gem/rubocop-sane#lib/rubocop/sane.rb:9
RuboCop::Sane::CONFIG_DEFAULT = T.let(T.unsafe(nil), Pathname)

# pkg:gem/rubocop-sane#lib/rubocop/sane.rb:6
class RuboCop::Sane::Error < ::StandardError; end

# pkg:gem/rubocop-sane#lib/rubocop/sane.rb:8
RuboCop::Sane::PROJECT_ROOT = T.let(T.unsafe(nil), Pathname)

# A plugin that integrates RuboCop Sane with RuboCop's plugin system.
#
# pkg:gem/rubocop-sane#lib/rubocop/sane/plugin.rb:8
class RuboCop::Sane::Plugin < ::LintRoller::Plugin
  # pkg:gem/rubocop-sane#lib/rubocop/sane/plugin.rb:9
  def about; end

  # pkg:gem/rubocop-sane#lib/rubocop/sane/plugin.rb:22
  def rules(_context); end

  # @return [Boolean]
  #
  # pkg:gem/rubocop-sane#lib/rubocop/sane/plugin.rb:18
  def supported?(context); end
end

# pkg:gem/rubocop-sane#lib/rubocop/sane/version.rb:5
RuboCop::Sane::VERSION = T.let(T.unsafe(nil), String)
