# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `wannabe_bool` gem.
# Please instead update this file by running `bin/tapioca gem wannabe_bool`.


# pkg:gem/wannabe_bool#lib/wannabe_bool/boolean.rb:14
class FalseClass
  include ::WannabeBool::Aliasing
  include ::WannabeBool::Boolean
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/nil.rb:10
class NilClass
  include ::WannabeBool::Aliasing
  include ::WannabeBool::Nil
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/numeric.rb:10
class Numeric
  include ::Comparable
  include ::WannabeBool::Aliasing
  include ::WannabeBool::Numeric
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:17
class String
  include ::Comparable
  include ::WannabeBool::Aliasing
  include ::WannabeBool::String
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/symbol.rb:10
class Symbol
  include ::Comparable
  include ::WannabeBool::Aliasing
  include ::WannabeBool::Symbol
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/boolean.rb:10
class TrueClass
  include ::WannabeBool::Aliasing
  include ::WannabeBool::Boolean
end

# pkg:gem/wannabe_bool#lib/wannabe_bool.rb:2
module WannabeBool
  extend ::WannabeBool::Configuration
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/aliasing.rb:2
module WannabeBool::Aliasing
  # @raise [NotImplementedError]
  #
  # pkg:gem/wannabe_bool#lib/wannabe_bool/aliasing.rb:8
  def to_b; end

  class << self
    # @private
    #
    # pkg:gem/wannabe_bool#lib/wannabe_bool/aliasing.rb:3
    def included(base); end
  end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/attributes.rb:2
module WannabeBool::Attributes
  mixes_in_class_methods ::WannabeBool::Attributes::ClassMethods

  class << self
    # @private
    #
    # pkg:gem/wannabe_bool#lib/wannabe_bool/attributes.rb:3
    def included(base); end
  end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/attributes.rb:7
module WannabeBool::Attributes::ClassMethods
  # pkg:gem/wannabe_bool#lib/wannabe_bool/attributes.rb:8
  def attr_wannabe_bool(*attributes); end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/boolean.rb:2
module WannabeBool::Boolean
  include ::WannabeBool::Aliasing

  # pkg:gem/wannabe_bool#lib/wannabe_bool/boolean.rb:3
  def to_b; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/boolean.rb:7
  def to_bool; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/boolean.rb:7
  def to_boolean; end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/configuration.rb:2
module WannabeBool::Configuration
  # pkg:gem/wannabe_bool#lib/wannabe_bool/configuration.rb:9
  def invalid_value_behaviour; end

  # @raise [ArgumentError]
  #
  # pkg:gem/wannabe_bool#lib/wannabe_bool/configuration.rb:3
  def invalid_value_behaviour=(behaviour); end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:2
module WannabeBool::InvalidValueBehaviour; end

# pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:15
module WannabeBool::InvalidValueBehaviour::Error
  class << self
    # @raise [ArgumentError]
    #
    # pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:16
    def call; end
  end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:3
module WannabeBool::InvalidValueBehaviour::False
  class << self
    # pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:4
    def call; end
  end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:9
module WannabeBool::InvalidValueBehaviour::Nil
  class << self
    # pkg:gem/wannabe_bool#lib/wannabe_bool/invalid_value_behaviour.rb:10
    def call; end
  end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/nil.rb:2
module WannabeBool::Nil
  include ::WannabeBool::Aliasing

  # pkg:gem/wannabe_bool#lib/wannabe_bool/nil.rb:3
  def to_b; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/nil.rb:7
  def to_bool; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/nil.rb:7
  def to_boolean; end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/numeric.rb:2
module WannabeBool::Numeric
  include ::WannabeBool::Aliasing

  # pkg:gem/wannabe_bool#lib/wannabe_bool/numeric.rb:3
  def to_b; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/numeric.rb:7
  def to_bool; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/numeric.rb:7
  def to_boolean; end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:2
module WannabeBool::String
  include ::WannabeBool::Aliasing

  # pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:6
  def to_b; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:14
  def to_bool; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:14
  def to_boolean; end
end

# pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:4
WannabeBool::String::FALSES = T.let(T.unsafe(nil), Array)

# pkg:gem/wannabe_bool#lib/wannabe_bool/string.rb:3
WannabeBool::String::TRUES = T.let(T.unsafe(nil), Array)

# pkg:gem/wannabe_bool#lib/wannabe_bool/symbol.rb:2
module WannabeBool::Symbol
  include ::WannabeBool::Aliasing

  # pkg:gem/wannabe_bool#lib/wannabe_bool/symbol.rb:3
  def to_b; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/symbol.rb:7
  def to_bool; end

  # pkg:gem/wannabe_bool#lib/wannabe_bool/symbol.rb:7
  def to_boolean; end
end
